# Generated by Django 3.2.1 on 2021-05-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=30, verbose_name='Sobrenome')),
                ('email', models.CharField(max_length=50, verbose_name='e-mail')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de Registro')),
            ],
        ),
    ]
