# Generated by Django 3.2.1 on 2021-05-05 15:17

from django.db import migrations

def create_data(apps, schema_editor):
    Api = apps.get_model('api', 'Api')
    Api(first_name='Joe', last_name='SilveStar', email="joesilverstar@email.com").save()
    

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
            migrations.RunPython(create_data),
    ]
